framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLogin",1))
value <- c(ll1000_JAVA_ee)
data_ll1000ee <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLogin",1))
value <- c(ll1000_JAVA_ef)
data_ll1000ef <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLogin",1))
value <- c(ll1000_JAVA_ec)
data_ll1000ec <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLogin",1))
value <- c(ll1000_JAVA_mm)
data_ll1000mm <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLogin",1))
value <- c(ll1000_JAVA_hs)
data_ll1000hs <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLogin",1))
value <- c(ll1000_JAVA_ha)
data_ll1000ha <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLogin",1))
value <- c(ll1000_JAVA_hf)
data_ll1000hf <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLoginEnc",1))
value <- c(lle1000_JAVA_ee)
data_lle1000ee <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLoginEnc",1))
value <- c(lle1000_JAVA_ef)
data_lle1000ef <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLoginEnc",1))
value <- c(lle1000_JAVA_ec)
data_lle1000ec <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLoginEnc",1))
value <- c(lle1000_JAVA_mm)
data_lle1000mm <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLoginEnc",1))
value <- c(lle1000_JAVA_hs)
data_lle1000hs <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLoginEnc",1))
value <- c(lle1000_JAVA_ha)
data_lle1000ha <- data.frame(benchmark,framework,value)
framework <- c(rep("JAVA", 30))
benchmark <- c(rep("localLoginEnc",1))
value <- c(lle1000_JAVA_hf)
data_lle1000hf <- data.frame(benchmark,framework,value)
test_allData_ENERGY<- rbind(data_ll1000ee,data_lle1000ee)
test_allData_FOREGROUND_TIME<- rbind(data_ll1000ef,data_lle1000ef)
test_allData_CPU_TIME<- rbind(data_ll1000ec,data_lle1000ec)
test_allData_MEMORY<- rbind(data_ll1000mm,data_lle1000mm)
test_allData_HEAP_SIZE<- rbind(data_ll1000hs,data_lle1000hs)
test_allData_HEAP_ALLOC<- rbind(data_ll1000ha,data_lle1000ha)
test_allData_HEAP_FREE<- rbind(data_ll1000hf,data_lle1000hf)
